### ISSUE TITLE
Video in the home page

### ISSUE THREAD

**Issue by lathangi** [CalamariFritti/webDoc2021#1]
Dear Client,
We are not able to access the video that has been provided to be used in the index page.
Please provide us with an alternative video.

**Comment by CalamariFritti** [comment]
Hello Team, 
good to hear from you. I have already prepared new video content with a bit better quality.
Can you elaborate what was the problem with accessing the video? Fileformat?
I will try to convert the new video material to .mp4 which should be good for this purpose here? 
Also the video is/was originally in .mov-format and should be accessible with for example VLC media player.

thanks and best regards
(commit with updated videos will follow soon)

**Comment by CalamariFritti** [comment]
and hello again,

the new videos are now available, also the old video file has been renamed (but i left it in the repo, just in case). 
If these changes provide a valid solution to your problems, please close this issue. 
Thank you.

**Comment by lathangi** [comment]
Yes, it is now accessible.
