### ISSUE TITLE
Problems rectified by developers!

### ISSUE THREAD

**Issue by Philippaul** [CalamariFritti/webDoc2021#4]
Dear client,
    Our report goes as follows,
1. Now your video is available in the home page and it looks beautiful (Nice video and it suits the background).
2. Since we currently don't have any database for storing the responses from the form it is unable to store and retrieve responses. But we can upgrade it according to your wish in assignment-2c.
3. As you suggested we have enlarged the company icon and also added an additional feature of redirecting back to the homepage when the user clicks the company logo.
   This is for you insight on the site. If you have any query feel free to raise an issue and we are ready to solve it. Please reply to this issue to close this.
Thank you! Have a nice day!

**Comment by CalamariFritti** [comment]
Looks good so far. Nice job with the video!
