### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by Philippaul** [CalamariFritti/webDoc2021#6]
Dear Client,
    Please do provide us with the github page link for your repo, so that we can host it.
Thanks you

**Comment by CalamariFritti** [comment]
I just followed the instructions given in the course material:
https://calamarifritti.github.io/webDoc2021/

this should be the link, though there is nothing published (yet).
the _config.yml file now exists ans should be editable.

**Comment by Philippaul** [comment]
Yeah this is it! Thanks for stating!
